name: Project Automation
on:
  issues:
    types: [opened, closed, reopened]
  pull_request:
    types: [opened, closed, reopened, merged]
jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Add issue to project
        if: github.event_name == 'issues'
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: >
            https://github.com/users/NMetAUbyMI/projects/2
          github-token: ${{ secrets.GITHUB_TOKEN }}